### PR TITLE
fix python semantic highlighting/expand more token support

### PR DESCRIPTION
**Pull request by akthe-at**
Love your theme, noticed two things though.

LSP semantic highlights didn't work with python/basedpyright lsp and when I went to fork and adjust/fix those I noticed there were still some more tokens needed. I have added them basked on Folke's tokens from Tokyonight. However, I don't think this is all of them and may need more added or modified over time.

Lua Example:
image

Python Example:
image

SQL Example:
image

R Example:
image

Djangohtml example:
image

### CODE REVIEW

**Comment by jacobrreed** [comment]
So originally I essentially copied how Mofiqul dracula theme was and substituted colors but maybe I should just fork tokyonight and sub colors there since Folke's implementation is probably much better

**Comment by akthe-at** [comment]
Thanks for taking the PR in the short term, that will help with quality of life in the meanwhile. However, I think your above idea isn't bad, I think folke has a very exhaustive codebase for supporting a lot of the ui elements and languages in neovim.

It seems like that would be a big investment though?

**Comment by jacobrreed** [comment]
> It seems like that would be a big investment though?
 I dont think it will be too bad, i'll look into it, tokyonight itself isnt that bed, i just have to erase the remnants of the other styles

**Comment by jacobrreed** [comment]
Opened a branch and got it mostly working just need to adjust some colors and get lualine working, after that'll Ill merge it to master

**Comment by jacobrreed** [comment]
> oth

oh well, i think its in a better place now

**Pull request merged**
